# Site settings
title: Lights and Wires in a Box
description: 'Thoughts about business, people and tech from a grumpy startup CTO'
url: 'http://joshgerdes.com/jekyll-uno'
baseurl: '/'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Steve Creedon'
  email: steve@creedon.me
  twitter_username: stevecreedon
  facebook_username: stevecreedon
  github_username:  stevecreedon
  linkedin_username:  stevecreedon

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
